name: Deploy Laravel Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SSH client
        run: sudo apt-get install -y sshpass

      - name: Deploy to Server via SSH
        env:
          SSH_PASS: ${{ secrets.SSH_PASS }}
        run: |
          sshpass -p "$SSH_PASS" ssh -o StrictHostKeyChecking=no root@80.78.240.29 << 'EOF'
            cd /var/www/api.mpstats.space
            git pull origin main

            # Use the correct paths for PHP and Composer
            composer install --no-interaction --prefer-dist --optimize-autoloader
            php artisan migrate --force
            php artisan optimize:clear
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache

            # Restart PHP-FPM (make sure the correct service is specified)
            sudo systemctl restart php8.2-fpm
          EOF
